# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produttore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azienda', models.CharField(max_length=50)),
                ('contatto', models.CharField(max_length=50)),
                ('citta', models.CharField(max_length=50)),
                ('regione', models.CharField(max_length=20)),
                ('acquisizione', models.DateField(null=True)),
                ('capacita', models.IntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('tel', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articolo', models.CharField(max_length=50)),
                ('genere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.Genere')),
            ],
        ),
        migrations.AddField(
            model_name='produttore',
            name='settore',
            field=models.ManyToManyField(to='gestione.Settore'),
        ),
    ]
