# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 17:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regione', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Carico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('cassaexit', models.IntegerField(blank=True, default=0, null=True)),
                ('cassa', models.IntegerField(blank=True, default=0, null=True)),
                ('data', models.DateField(default=datetime.date.today)),
                ('datafatt', models.DateField(default=datetime.date.today)),
                ('bolla', models.CharField(max_length=20, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('p', models.SmallIntegerField(default=0)),
                ('cv', models.IntegerField(blank=True, default=0, null=True)),
                ('mrg', models.SmallIntegerField(default=0)),
                ('fattimp', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
                ('fatt', models.CharField(max_length=10, null=True)),
                ('pagato', models.BooleanField(default=0)),
                ('note', models.TextField(default='', max_length=30)),
                ('qn', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('tara', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True)),
                ('qcv', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('fattcv', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=20, null=True)),
                ('costi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('ricavi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regione', models.CharField(max_length=20, null=True)),
                ('citta', models.CharField(max_length=50, null=True)),
                ('azienda', models.CharField(blank=True, default=' ', max_length=50, unique=True)),
                ('indirizzo', models.CharField(blank=True, default=' ', max_length=60, null=True)),
                ('acquisizione', models.DateField(default=datetime.date.today)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tel', models.CharField(blank=True, default=' ', max_length=15, null=True)),
                ('trpag', models.IntegerField(blank=True, default=0, null=True)),
                ('pi', models.CharField(blank=True, default=' ', max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='contoce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=2)),
                ('sub', models.CharField(max_length=2)),
                ('ssub', models.CharField(default='', max_length=2)),
                ('dtreg', models.DateField(default=datetime.date.today)),
                ('doc', models.CharField(max_length=20, null=True)),
                ('dtdoc', models.DateField(default=datetime.date.today)),
                ('dare', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('avere', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('regis', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='contocln',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=2)),
                ('sub', models.CharField(max_length=2)),
                ('ssub', models.CharField(default='', max_length=2)),
                ('dtreg', models.DateField(default=datetime.date.today)),
                ('doc', models.CharField(max_length=20, null=True)),
                ('dtdoc', models.DateField(default=datetime.date.today)),
                ('dare', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('avere', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('regis', models.CharField(max_length=60, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='contofrn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=2)),
                ('sub', models.CharField(max_length=2)),
                ('ssub', models.CharField(default='', max_length=2)),
                ('dtreg', models.DateField(default=datetime.date.today)),
                ('doc', models.CharField(max_length=20, null=True)),
                ('dtdoc', models.DateField(default=datetime.date.today)),
                ('dare', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('avere', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('regis', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='contosp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=2)),
                ('sub', models.CharField(max_length=2)),
                ('ssub', models.CharField(default='', max_length=2)),
                ('dtreg', models.DateField(default=datetime.date.today)),
                ('doc', models.CharField(max_length=20, null=True)),
                ('dtdoc', models.DateField(default=datetime.date.today)),
                ('dare', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('avere', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('regis', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExCsBl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolla', models.CharField(max_length=20, null=True)),
                ('facc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('trasporto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('vari', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('datafatt', models.DateField(default=datetime.date.today)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('p', models.SmallIntegerField(default=0)),
                ('cv', models.IntegerField(blank=True, default=0, null=True)),
                ('fattimp', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
                ('fatt', models.CharField(max_length=10, null=True)),
                ('pagato', models.BooleanField(default=0)),
                ('note', models.TextField(default='', max_length=30)),
                ('qn', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('cassaexit', models.IntegerField(blank=True, default=0, null=True)),
                ('cassa', models.IntegerField(blank=True, default=0, null=True)),
                ('q', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('data', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IDcod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=60, null=True)),
                ('genere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.Genere')),
            ],
        ),
        migrations.CreateModel(
            name='ivacliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtreg', models.DateField(default=datetime.date.today)),
                ('prot', models.IntegerField(blank=True, default=0, null=True)),
                ('dtfatt', models.DateField(default=datetime.date.today)),
                ('fatt', models.CharField(max_length=20, null=True)),
                ('nome', models.CharField(max_length=20, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2, null=True)),
                ('tot', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('imp', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('erario', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('esenzione', models.CharField(max_length=20, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ivaforn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtreg', models.DateField(default=datetime.date.today)),
                ('prot', models.IntegerField(blank=True, default=0, null=True)),
                ('dtfatt', models.DateField(default=datetime.date.today)),
                ('fatt', models.CharField(max_length=20, null=True)),
                ('nome', models.CharField(max_length=20, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2, null=True)),
                ('tot', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('imp', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('erario', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('esenzione', models.CharField(max_length=20, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtreg', models.DateField(default=datetime.date.today)),
                ('prot', models.IntegerField(blank=True, default=0, null=True)),
                ('doc', models.CharField(max_length=20, null=True)),
                ('dtdoc', models.DateField(default=datetime.date.today)),
                ('descr', models.CharField(max_length=60, null=True)),
                ('conto', models.CharField(max_length=10, null=True)),
                ('dare', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('avere', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('giorni', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Preferenza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artic', models.CharField(max_length=20, null=True)),
                ('margine', models.FloatField(max_length=20, null=True)),
                ('fatturato', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Produttore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regione', models.CharField(max_length=20, null=True)),
                ('citta', models.CharField(max_length=50, null=True)),
                ('azienda', models.CharField(blank=True, default=' ', max_length=50, unique=True)),
                ('contatto', models.CharField(blank=True, default=' ', max_length=50)),
                ('indirizzo', models.CharField(blank=True, default=' ', max_length=60, null=True)),
                ('acquisizione', models.DateField(default=datetime.date.today)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tel', models.CharField(blank=True, default=' ', max_length=15, null=True)),
                ('trpag', models.IntegerField(blank=True, default=0, null=True)),
                ('margine', models.IntegerField(blank=True, default=0, null=True)),
                ('fatturato', models.IntegerField(blank=True, default=0, null=True)),
                ('pi', models.CharField(default=' ', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.IntegerField(blank=True, default=0, null=True)),
                ('data', models.DateField(default=datetime.date.today)),
                ('idcod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.IDcod')),
            ],
        ),
        migrations.CreateModel(
            name='saldocliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attivo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('passivo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestione.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='saldoprod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attivo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('passivo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('prod', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestione.Produttore')),
            ],
        ),
        migrations.CreateModel(
            name='Scarico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('cassa', models.IntegerField(blank=True, default=0, null=True)),
                ('prezzo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('data', models.DateField(default=datetime.date.today)),
                ('fattura', models.TextField(blank=True, max_length=10, null=True)),
                ('lotto', models.CharField(max_length=50, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2, null=True)),
                ('scadenza', models.DateField(default=datetime.date.today)),
                ('pagato', models.BooleanField(default=0)),
                ('note', models.TextField(default='', max_length=30)),
                ('tara', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2, null=True)),
                ('rs', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('rscassa', models.IntegerField(blank=True, default=0, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.Cliente')),
                ('idcod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.IDcod')),
            ],
        ),
        migrations.CreateModel(
            name='Settore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articolo', models.CharField(max_length=50, null=True)),
                ('genere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.Genere')),
            ],
        ),
        migrations.CreateModel(
            name='Sito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citta', models.CharField(max_length=50, null=True)),
                ('sigla', models.CharField(max_length=5, null=True)),
                ('comune', models.CharField(max_length=2, null=True)),
                ('cap', models.CharField(max_length=6, null=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Sospese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('cassa', models.IntegerField(blank=True, default=0, null=True)),
                ('prezzo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('data', models.DateField(default=datetime.date.today)),
                ('fatturas', models.TextField(blank=True, max_length=10, null=True)),
                ('lotto', models.CharField(max_length=20, null=True)),
                ('tara', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.Cliente')),
                ('idcod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.IDcod')),
            ],
        ),
        migrations.CreateModel(
            name='sp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=20, null=True)),
                ('attivo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('passivo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specifica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('settore', models.ManyToManyField(to='gestione.Settore')),
            ],
        ),
        migrations.CreateModel(
            name='Tara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont', models.CharField(max_length=20, null=True)),
                ('q', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='trasporto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('cassa', models.IntegerField(blank=True, default=0, null=True)),
                ('prezzo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('data', models.DateField(default=datetime.date.today)),
                ('ddt', models.TextField(blank=True, max_length=10, null=True)),
                ('lotto', models.CharField(max_length=50, null=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('tara', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.Cliente')),
                ('idcod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.IDcod')),
            ],
        ),
        migrations.AddField(
            model_name='produttore',
            name='settore',
            field=models.ManyToManyField(to='gestione.Settore'),
        ),
        migrations.AlterUniqueTogether(
            name='preferenza',
            unique_together=set([('artic', 'margine')]),
        ),
        migrations.AddField(
            model_name='idcod',
            name='produttore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.Produttore'),
        ),
        migrations.AddField(
            model_name='idcod',
            name='settore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.Settore'),
        ),
        migrations.AddField(
            model_name='idcod',
            name='specifica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.Specifica'),
        ),
        migrations.AddField(
            model_name='idcod',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.Tipo'),
        ),
        migrations.AddField(
            model_name='excsbl',
            name='produttore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.Produttore'),
        ),
        migrations.AddField(
            model_name='contofrn',
            name='forn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.Produttore'),
        ),
        migrations.AddField(
            model_name='carico',
            name='excsbl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.ExCsBl'),
        ),
        migrations.AddField(
            model_name='carico',
            name='idcod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.IDcod'),
        ),
    ]
