# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regione', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citta', models.CharField(max_length=20, null=True)),
                ('comune', models.CharField(max_length=30, null=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.Area')),
            ],
        ),
        migrations.RemoveField(
            model_name='produttore',
            name='citta',
        ),
        migrations.RemoveField(
            model_name='produttore',
            name='regione',
        ),
        migrations.AddField(
            model_name='produttore',
            name='indirizzo',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
