# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regione', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Preferenza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artic', models.CharField(max_length=20, null=True)),
                ('margine', models.FloatField(max_length=20, null=True)),
                ('fatturato', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citta', models.CharField(max_length=20, null=True)),
                ('sigla', models.CharField(max_length=5, null=True)),
                ('comune', models.CharField(max_length=30, null=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.Area')),
            ],
        ),
        migrations.AddField(
            model_name='produttore',
            name='fatturato',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='produttore',
            name='indirizzo',
            field=models.CharField(blank=True, default=' ', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='produttore',
            name='margine',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='produttore',
            name='trpag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='produttore',
            name='acquisizione',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='produttore',
            name='azienda',
            field=models.CharField(blank=True, default=' ', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='produttore',
            name='capacita',
            field=models.CharField(blank=True, default=' ', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='produttore',
            name='citta',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='produttore',
            name='contatto',
            field=models.CharField(blank=True, default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='produttore',
            name='email',
            field=models.EmailField(blank=True, default=' ', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='produttore',
            name='regione',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='produttore',
            name='tel',
            field=models.CharField(blank=True, default=' ', max_length=15, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='preferenza',
            unique_together=set([('artic', 'margine')]),
        ),
    ]
