# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0002_auto_20170702_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='sito',
            name='sigla',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
