# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0004_auto_20170702_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produttore',
            name='azienda',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
