# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0005_auto_20170703_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produttore',
            name='azienda',
            field=models.CharField(max_length=50),
        ),
    ]
