# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0007_auto_20170703_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferenza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regione', models.CharField(max_length=20, null=True)),
                ('Margine', models.FloatField(max_length=20, null=True)),
                ('Fatturato', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='settore',
            name='preferenza',
            field=models.ManyToManyField(to='gestione.Preferenza'),
        ),
    ]
