# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0009_auto_20170706_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settore',
            name='preferenza',
        ),
    ]
