# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0010_remove_settore_preferenza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferenza',
            old_name='regione',
            new_name='artic',
        ),
        migrations.AddField(
            model_name='produttore',
            name='preferenza',
            field=models.ManyToManyField(to='gestione.Preferenza'),
        ),
        migrations.AlterUniqueTogether(
            name='preferenza',
            unique_together=set([('artic', 'margine')]),
        ),
    ]
