# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0011_auto_20170706_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produttore',
            name='preferenza',
        ),
    ]
