# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0014_auto_20170710_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produttore',
            name='azienda',
            field=models.CharField(blank=True, default=' ', max_length=50, unique=True),
        ),
    ]
