# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0015_auto_20170719_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produttore',
            name='acquisizione',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produttore',
            name='capacita',
            field=models.CharField(blank=True, default=' ', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='produttore',
            name='contatto',
            field=models.CharField(blank=True, default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='produttore',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='produttore',
            name='fatturato',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='produttore',
            name='indirizzo',
            field=models.CharField(blank=True, default=' ', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='produttore',
            name='margine',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='produttore',
            name='tel',
            field=models.CharField(blank=True, default=' ', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='produttore',
            name='trpag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
