# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0016_auto_20170719_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produttore',
            name='capacita',
            field=models.CharField(blank=True, default='Bassa ', max_length=10, null=True),
        ),
    ]
