# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 14:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0017_auto_20170719_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produttore',
            name='acquisizione',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
