# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0020_auto_20170724_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settore',
            name='articolo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
