# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 12:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0021_auto_20170720_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produttore',
            name='acquisizione',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
