# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0021_auto_20170725_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='produttore',
            name='pi',
            field=models.CharField(blank=True, default=' ', max_length=11, null=True),
        ),
    ]
