# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0022_auto_20170720_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produttore',
            name='acquisizione',
            field=models.DateField(blank=True, null=True),
        ),
    ]
