# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0024_specifica'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDcod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=30, null=True)),
                ('genere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.Genere')),
                ('settore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.Settore')),
                ('specifica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.Specifica')),
            ],
        ),
        migrations.AddField(
            model_name='produttore',
            name='cod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.IDcod'),
        ),
    ]
