# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0027_auto_20170731_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specifica',
            name='settore',
        ),
        migrations.AddField(
            model_name='specifica',
            name='settore',
            field=models.ManyToManyField(to='gestione.Settore'),
        ),
    ]
