# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0028_auto_20170801_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specifica',
            name='nome',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
