# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 08:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0029_auto_20170801_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.IntegerField(blank=True, default=0, null=True)),
                ('data', models.DateField(default=datetime.date.today)),
                ('idcod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.IDcod')),
            ],
        ),
    ]
