# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0030_carico'),
    ]

    operations = [
        migrations.AddField(
            model_name='carico',
            name='bolla',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
