# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 14:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0032_auto_20170803_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produttore',
            name='acquisizione',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
