# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 07:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0033_auto_20170808_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scarico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.IntegerField(blank=True, default=0, null=True)),
                ('prezzo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('data', models.DateField(default=datetime.date.today)),
                ('fattura', models.TextField(blank=True, max_length=10, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.Cliente')),
                ('idcod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.IDcod')),
            ],
        ),
        migrations.AddField(
            model_name='genere',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='produttore',
            name='acquisizione',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
