# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0037_auto_20170813_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sospese',
            name='q',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
