# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0040_auto_20170813_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sospese',
            name='prezzo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
