# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0044_auto_20170816_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tel',
            field=models.CharField(blank=True, default=' ', max_length=15, null=True),
        ),
    ]
