# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-29 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0048_auto_20170829_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carico',
            name='q',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
