# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0049_auto_20170829_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='carico',
            name='cassa',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='scarico',
            name='cassa',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sospese',
            name='cassa',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='q',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
