# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0051_pagamento_prodotto'),
    ]

    operations = [
        migrations.AddField(
            model_name='carico',
            name='qu',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
