# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0054_auto_20170906_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carico',
            name='cassaout',
        ),
    ]
