# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0055_remove_carico_cassaout'),
    ]

    operations = [
        migrations.AddField(
            model_name='carico',
            name='cassaout',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
