# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0056_carico_cassaout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carico',
            name='cassa',
        ),
    ]
