# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0057_remove_carico_cassa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carico',
            name='cassaout',
        ),
        migrations.AddField(
            model_name='carico',
            name='cassa',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
