# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0058_auto_20170907_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='carico',
            name='cassaexit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
