# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-11 10:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0059_carico_cassaexit'),
    ]

    operations = [
        migrations.CreateModel(
            name='trasporto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('cassa', models.IntegerField(blank=True, default=0, null=True)),
                ('prezzo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('data', models.DateField(default=datetime.date.today)),
                ('ddt', models.TextField(blank=True, max_length=10, null=True)),
                ('lotto', models.CharField(max_length=5, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.Cliente')),
                ('idcod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.IDcod')),
            ],
        ),
    ]
