# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-12 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0060_trasporto'),
    ]

    operations = [
        migrations.AddField(
            model_name='scarico',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2, null=True),
        ),
    ]
