# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-12 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0061_scarico_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='trasporto',
            name='status',
            field=models.SmallIntegerField(default=0, max_length=1),
        ),
    ]
