# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0062_trasporto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trasporto',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
