# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0063_auto_20170918_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='email',
            new_name='contatto',
        ),
    ]
