# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0064_auto_20170918_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contatto',
        ),
    ]
