# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0065_remove_cliente_contatto'),
    ]

    operations = [
        migrations.AddField(
            model_name='carico',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
