# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-21 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0068_carico_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carico',
            name='p',
            field=models.BooleanField(default=False),
        ),
    ]
