# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0071_carico_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carico',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
