# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0075_carico_fatt'),
    ]

    operations = [
        migrations.AddField(
            model_name='carico',
            name='fattimp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True),
        ),
    ]
