# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-08 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0077_auto_20170927_1544'),
        ('gestione', '0002_auto_20170719_1650'),
        ('gestione', '0023_auto_20170720_1235'),
    ]

    operations = [
    ]
