# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-08 07:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0078_merge_20171008_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produttore',
            name='acquisizione',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='produttore',
            name='capacita',
            field=models.CharField(blank=True, default='Bassa ', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='produttore',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
