# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-08 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0081_remove_saldo_tst'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldo',
            name='tst',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
