# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0083_remove_saldo_tst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont', models.CharField(max_length=5, null=True)),
                ('q', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True)),
            ],
        ),
    ]
