# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0084_tara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tara',
            name='q',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
