# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0085_auto_20171010_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tara',
            name='cont',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tara',
            name='q',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True),
        ),
    ]
