# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-12 12:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0086_auto_20171010_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='scarico',
            name='pagato',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='scarico',
            name='scadenza',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
