# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-12 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0087_auto_20171012_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='giorni',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scarico',
            name='note',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
