# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-15 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0089_auto_20171013_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='scarico',
            name='tara',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='sospese',
            name='tara',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='trasporto',
            name='tara',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2, null=True),
        ),
    ]
