# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-16 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0090_auto_20171015_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='ce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=20, null=True)),
                ('costi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('ricavi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=20, null=True)),
                ('attivo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('passivo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
            ],
        ),
    ]
