# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-20 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0091_ce_sp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produttore',
            name='capacita',
        ),
        migrations.AddField(
            model_name='carico',
            name='pagato',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cod',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='produttore',
            name='cod',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='produttore',
            name='pi',
            field=models.CharField(max_length=11),
        ),
    ]
