# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-20 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0092_auto_20171020_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produttore',
            name='pi',
            field=models.CharField(default=' ', max_length=11),
        ),
    ]
