# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-20 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0093_auto_20171020_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='carico',
            name='note',
            field=models.TextField(default='', max_length=30),
        ),
    ]
