# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-21 16:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0094_carico_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ivacliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtreg', models.DateField(default=datetime.date.today)),
                ('prot', models.IntegerField(blank=True, default=0, null=True)),
                ('dtfatt', models.DateField(default=datetime.date.today)),
                ('fatt', models.CharField(max_length=20, null=True)),
                ('nome', models.CharField(max_length=20, null=True)),
                ('tot', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('imp', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('erario', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('esenzione', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
