# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-28 17:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0096_auto_20171027_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtreg', models.DateField(default=datetime.date.today)),
                ('prot', models.IntegerField(blank=True, default=0, null=True)),
                ('doc', models.CharField(max_length=20, null=True)),
                ('dtdoc', models.DateField(default=datetime.date.today)),
                ('desc', models.CharField(max_length=30, null=True)),
                ('conto', models.CharField(max_length=10, null=True)),
                ('dare', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('avere', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
            ],
        ),
    ]
