# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 21:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0097_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='carico',
            name='datafatt',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
