# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0098_carico_datafatt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scarico',
            name='lotto',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sospese',
            name='lotto',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trasporto',
            name='lotto',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
