# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-22 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0101_scarico_rscassa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scarico',
            name='lotto',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
