# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0103_auto_20171125_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='sito',
            name='cap',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
