# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0106_auto_20171127_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='citta',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produttore',
            name='citta',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
