# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0107_auto_20171127_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='desc',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
