# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0110_scarico_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scarico',
            name='saldo',
        ),
        migrations.AddField(
            model_name='ivacliente',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True),
        ),
    ]
