# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-09 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0111_auto_20171208_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='ivaforn',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True),
        ),
    ]
