# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0112_ivaforn_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carico',
            name='tara',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2, null=True),
        ),
    ]
