# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0113_carico_tara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carico',
            name='tara',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True),
        ),
    ]
