# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0115_saldocliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='saldoprod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attivo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('passivo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('prod', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestione.Produttore')),
            ],
        ),
    ]
