# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0120_contocln'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contocln',
            old_name='subcod',
            new_name='sub',
        ),
        migrations.AddField(
            model_name='contocln',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.Cliente'),
        ),
    ]
