# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 17:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0121_auto_20180204_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='contoce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=2)),
                ('sub', models.CharField(max_length=2)),
                ('dtreg', models.DateField(default=datetime.date.today)),
                ('doc', models.CharField(max_length=20, null=True)),
                ('dtdoc', models.DateField(default=datetime.date.today)),
                ('dare', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('avere', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('regis', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='contosp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=2)),
                ('sub', models.CharField(max_length=2)),
                ('dtreg', models.DateField(default=datetime.date.today)),
                ('doc', models.CharField(max_length=20, null=True)),
                ('dtdoc', models.DateField(default=datetime.date.today)),
                ('dare', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('avere', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('regis', models.CharField(max_length=60, null=True)),
            ],
        ),
    ]
