# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0122_contoce_contosp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contoce',
            name='ssub',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='contocln',
            name='ssub',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='contosp',
            name='ssub',
            field=models.CharField(default='', max_length=2),
        ),
    ]
