# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 17:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0123_auto_20180205_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='contofrn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=2)),
                ('sub', models.CharField(max_length=2)),
                ('ssub', models.CharField(default='', max_length=2)),
                ('dtreg', models.DateField(default=datetime.date.today)),
                ('doc', models.CharField(max_length=20, null=True)),
                ('dtdoc', models.DateField(default=datetime.date.today)),
                ('dare', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('avere', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('regis', models.CharField(max_length=60, null=True)),
                ('forn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.Cliente')),
            ],
        ),
    ]
