# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0124_contofrn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contofrn',
            name='forn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.Produttore'),
        ),
    ]
