# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 21:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0125_auto_20180207_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='excsbl',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='excsbl',
            name='cv',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='excsbl',
            name='datafatt',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='excsbl',
            name='fatt',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='excsbl',
            name='fattimp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='excsbl',
            name='note',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='excsbl',
            name='p',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excsbl',
            name='pagato',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='excsbl',
            name='qn',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
