# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0126_auto_20180227_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='excsbl',
            name='cassa',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='excsbl',
            name='cassaexit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
