# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0127_auto_20180227_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='excsbl',
            name='q',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
