# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0128_excsbl_q'),
    ]

    operations = [
        migrations.AddField(
            model_name='excsbl',
            name='bolla',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
