# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 15:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0129_excsbl_bolla'),
    ]

    operations = [
        migrations.AddField(
            model_name='excsbl',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
