# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0131_excsbl_produttore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excsbl',
            name='produttore',
        ),
    ]
