# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0133_excsbl_produttore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='desc',
            new_name='descr',
        ),
        migrations.AddField(
            model_name='carico',
            name='fattcv',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='carico',
            name='qcv',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
